mybatis:
  #Mapper.xml所在的位置
  mapper-locations: classpath:mapper/*.xml
  #entity扫描的包名
  type-aliases-package: com.kdkj.py.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
